<?php

########################################################################
# Extension Manager/Repository config file for ext: "test_extension"
#
# Auto generated by Extbase Kickstarter 2010-05-25
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'test extension',
	'description' => 'some tests for the extbase_kickstarter',
	'category' => 'plugin',
	'author' => 'Stephan Petzl,Christian Kartnig,Sebastian Kurfürst',
	'author_email' => 'stephan.petzl@ajado.com,office@hahnepeter.de,sebastian@typo3.org',
	'author_company' => 'ajado,,',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>